#ifndef DATACONTROLLIB_GLOBAL_H
#define DATACONTROLLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATACONTROLLIB_LIBRARY)
#  define DATACONTROLLIB_EXPORT Q_DECL_EXPORT
#else
#  define DATACONTROLLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // DATACONTROLLIB_GLOBAL_H
